# -*- coding: utf-8 -*-
"""7-1-25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZH7q_Z-vKizCsYColAqCopEcCq-uCvk
"""

a="hello world"
b=a.upper()
print(b)

a="hello world"
b=a.lower()
print(b)

a="hello world"
b=a.swapcase()
print(b)

a="hello world"
b=a.title()
print(b)

a="hello world"
b=a.replace("hello","hi")
print(b)

def greet(name):
  print("hello,"+name+"!")
greet("Alice")

a="1234"
b=a.isdigit()
print(b)

a="1234asfghj"
b=a.isdigit()
print(b)

a=range(10)
print(a)

a=range(10)
b=list(a)
print(b)

#start, stop then steps
my_list=list(range(5,15,2))
print(my_list)

#function with return
def add_numbers(a,b):
  result = a+b
  return result
print(add_numbers(10,4))

#function with default
def greet(name,greeting="hello"):
  print(f"{greeting},{name}!")
greet("Alice")

#function with *arg
def calculate_sum(*args):
  total=sum(args)
  return total
print("sum of 1,2,3:",calculate_sum(1,2,3))
print("sum of 1,2,3,4:",calculate_sum(1,2,3,4))

correct_username='admin'
correct_password='1234'
while True:
  username=input("Enter your username:")
  password=input("Enter your password:")
  if username==correct_username and password ==correct_password:
    print("Login succesfully")
    break
  else:
    print("Invalid username or password.please try again")

#max
numbers = [10, 20, 30]
print(max(numbers))

#min
numbers = [10, 20, 30]
print(min(numbers))

#Function to Check if a Number is Even
def is_even(number):
    return number % 2 == 0

print(is_even(4))
print(is_even(5))

#Function to Reverse a String
def reverse_string(s):
    return s[::-1]

print(reverse_string("hello"))

#Function to Find the Maximum of Three Numbers
def find_max(a, b, c):
    return max(a, b, c)
print(find_max(10, 20, 15))